spring:
  jpa:
    show-sql: true
    database: H2
    database-platform: H2
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl_auto: none
        
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    initialize: true
    platform: H2